language: python
python:
 - "3.5"
 - "3.6"
 - "nightly"
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script:
  - python highscor.py < tests/testhighscor2.txt
  - python highscor_cmdline.py < tests/testhighscor_cmdline.txt
  - py.test
after_success:
  - coveralls
